<?php

namespace KeurGuiImmoBundle\Repository;

/**
 * BienPhotosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BienPhotosRepository extends \Doctrine\ORM\EntityRepository
{
}
