<?php

namespace KeurGuiImmoBundle\Repository;

/**
 * ParentBienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParentBienRepository extends \Doctrine\ORM\EntityRepository
{
}
