<?php

namespace KeurGuiImmoBundle\Repository;

/**
 * termesContratRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class termesContratRepository extends \Doctrine\ORM\EntityRepository
{
}
